server:
  port: 55002

spring:
  application:
    name: ms-user
  sleuth:
    enabled: true
    sampler:
      probability: 1
  datasource:
    url: ${DB_URL:jdbc:postgresql://linux.local:5432/sbwms}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWORD:abcd.1234}
  jpa:
    hibernate:
#      ddl-auto: validate
      ddl-auto: create
  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      time-to-live: 1h
  redis:
    port: ${CACHE_PORT:6379}
    host: ${CACHE_URL:linux.local}

key: ${SIGN_KEY:7R9SATCVDWEXGZH2J4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7Q8SATBUCWEXFY}

logging:
  file:
    name: ${LOG_URL:./ms-user.log}
    max-history: ${LOG_RETENTION_MAX_DAYS:14}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    level: ${LOG_LEVEL:DEBUG}